In [1]:
import numpy as np
import pandas as pd
# Warnings
import warnings
warnings.filterwarnings('ignore')

In [37]:
# Multiple Linear Regression
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings("ignore")
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.model_selection import train_test_split
import bisect
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn import linear_model
#     print('LinearRegression')
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_predict
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [103]:
def model(regressor,X_train, X_test, y_train, y_test):
    print(regressor)
    model1 = regressor.fit(X_train,y_train)
    print('train acc')
    print(model1.score(X_train, y_train))
    print('y_pred')
    y_pred = model1.predict(X_test)
    print('testing acc')
    print(r2_score(y_test,y_pred))
    #     print('testing acc')
    #     df1=pd.DataFrame(y_pred,columns=['pred'])
    #     df1['actual']=X_test
    #     print(df1)
    return y_pred
def multi(X_train, X_test, y_train, y_test):
    from sklearn import linear_model
    regressor = linear_model.LinearRegression()
    y_pred=model(regressor,X_train, X_test, y_train, y_test)
    return y_pred
def decision(X_train, X_test, y_train, y_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state = 0)
    y_pred=model(regressor,X_train, X_test, y_train, y_test)
    return y_pred
def random(X_train, X_test, y_train, y_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 40, random_state = 0)
    y_pred=model(regressor,X_train, X_test, y_train, y_test)
    return y_pred
def svr(X_train, X_test, y_train, y_test):
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'rbf')
    y_pred=model(regressor,X_train, X_test, y_train, y_test)
    return y_pred
def boost(X_train, X_test, y_train, y_test):
    from sklearn import ensemble
    params = {
    'n_estimators': 1,
    'max_depth': 1,
    'learning_rate': 1,
    'criterion': 'mse'
    }
    regressor = ensemble.GradientBoostingRegressor(**params)
    y_pred=model(regressor,X_train, X_test, y_train, y_test)
    return y_pred
def main(X_train, X_test, y_train, y_test):
    y_pred_multi=multi(X_train, X_test, y_train, y_test)
    y_pred_decision=decision(X_train, X_test, y_train, y_test)
    y_pred_random=random(X_train, X_test, y_train, y_test)
    # 	svr(X_train, X_test, y_train, y_test)	
    y_pred_boost=boost(X_train, X_test, y_train, y_test)
    return y_pred_multi,y_pred_decision,y_pred_random,y_pred_boost

In [104]:
city_day = pd.read_csv("city_day.csv")

In [105]:
city_day['Date'] =  pd.to_datetime(city_day['Date'],format='%Y-%m-%d')

In [106]:
year = city_day['Date'].dt.year
month = city_day['Date'].dt.month
day = city_day['Date'].dt.day

In [107]:
city_day.insert(loc=1, column='Year', value= year)
city_day.insert(loc=2, column='Month', value= month)
city_day.insert(loc=3, column='Date1', value= day)

In [108]:
city_day_ahm = city_day

In [109]:
city_day_ahm

,City,Year,Month,Date1,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015,1,1,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015,1,2,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015,1,3,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015,1,4,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015,1,5,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26214,Thiruvananthapuram,2020,4,27,2020-04-27,14.13,34.27,5.60,8.98,12.48,5.65,0.49,5.50,42.41,NaN,NaN,NaN,63.0,Satisfactory
26215,Thiruvananthapuram,2020,4,28,2020-04-28,23.84,44.32,6.27,10.01,13.80,5.73,0.44,5.62,44.55,NaN,NaN,NaN,60.0,Satisfactory
26216,Thiruvananthapuram,2020,4,29,2020-04-29,18.54,34.48,6.17,9.67,13.35,5.93,0.51,5.52,38.97,NaN,NaN,NaN,57.0,Satisfactory
26217,Thiruvananthapuram,2020,4,30,2020-04-30,20.57,48.19,6.28,9.52,13.56,5.84,0.46,5.32,39.23,NaN,NaN,NaN,57.0,Satisfactory
26218,Thiruvananthapuram,2020,5,1,2020-05-01,17.58,37.49,2.56,7.84,9.34,4.85,0.45,7.10,31.16,NaN,NaN,NaN,82.0,Satisfactory

In [110]:
city_day_ahm.Year.value_counts()

2019    6878
2018    6106
2017    4324
2016    3294
2020    2816
2015    2801
Name: Year, dtype: int64

In [111]:
# city_day_1_ahm = city_day_ahm.dropna(axis=0, how="all", subset=["PM2.5","PM10"], inplace=False)

In [112]:
# city_day_1_ahm

In [113]:
city_day_ahm_copy = city_day_ahm

In [114]:
avg_aqi_month = city_day_ahm.groupby(['Month']).AQI.mean()

In [115]:
avg_aqi_month = list(avg_aqi_month)

In [116]:
avg_aqi_month

[236.6812248995984,
 207.97628865979382,
 168.91903019213174,
 146.602658111824,
 159.1073619631902,
 142.4430709173715,
 113.9419014084507,
 115.17365269461078,
 116.74483596597813,
 193.5881690140845,
 251.53170189098998,
 234.69525839104955]

In [128]:
y_pred_multi,y_pred_decision,y_pred_random,y_pred_boost=main(X_train,X_test,Y_train,Y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
train acc
0.7429657883350512
y_pred
testing acc
0.7979501544965512
DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')
train acc
0.9914847265473956
y_pred
testing acc
0.5435444704350216
RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=40, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)
train acc
0.9499917250309333
y_pred
testing acc
0.7684450061984698
GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='mse', init=None,
                          learning_rate=1, loss='ls', max_depth=1,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=1,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)
train acc
0.46462712269182155
y_pred
testing acc
0.39177833532267736

In [126]:
df1 = pd.DataFrame(Y_test_df.values,columns=['actual'])
df1['multi']=y_pred_multi
df1['decision']=y_pred_decision
df1['random']=y_pred_random
df1['boost']=y_pred_boost
df1.to_csv('dfx.csv')